"use client"

import { Shield, Key, Eye, AlertTriangle, Lock, Zap, Globe, RefreshCw } from "lucide-react"

export function PasswordTips() {
  const strengthExamples = [
    {
      category: "Weak",
      color: "red",
      timeToBreak: "Seconds to Minutes",
      examples: [
        { password: "password", issue: "Common dictionary word" },
        { password: "123456", issue: "Sequential numbers" },
        { password: "qwerty", issue: "Keyboard pattern" },
        { password: "admin", issue: "Default/common term" },
      ],
    },
    {
      category: "Medium",
      color: "yellow",
      timeToBreak: "Hours to Days",
      examples: [
        { password: "Password123", issue: "Predictable capitalization + numbers" },
        { password: "John1990", issue: "Name + birth year" },
        { password: "Summer2024", issue: "Season + current year" },
        { password: "MyDog123", issue: "Personal info + simple numbers" },
      ],
    },
    {
      category: "Strong",
      color: "green",
      timeToBreak: "Centuries",
      examples: [
        { password: "Tr0pic@l$unset&Beach9!", issue: "Long, mixed characters, symbols" },
        { password: "Coffee#Moon$Dance7Cloud", issue: "Random words + symbols + numbers" },
        { password: "MyGr@ndm@L0ves2B@ke!", issue: "Personal phrase with substitutions" },
        { password: "Blu3$ky&R@inyD@y2024", issue: "Complex phrase with mixed elements" },
      ],
    },
  ]

  const creationMethods = [
    {
      title: "Passphrase Method",
      description: "Combine 4-6 random words with numbers and symbols",
      example: "correct horse battery staple",
      result: "Correct#Horse$Battery9Staple!",
      strength: "Very Strong",
    },
    {
      title: "Sentence Method",
      description: "Take first letters of a memorable sentence",
      example: "I love to drink 3 cups of coffee every morning at 7am",
      result: "ILtd3CoCoEm@7am!",
      strength: "Strong",
    },
    {
      title: "Substitution Method",
      description: "Replace letters with similar numbers/symbols",
      example: "MyFavoriteMovie",
      result: "MyF@v0r1t3M0v13!",
      strength: "Medium-Strong",
    },
    {
      title: "Random Generation",
      description: "Use a password manager to generate completely random passwords",
      example: "Generated by computer",
      result: "K9#mX$7nP@2wQ!5z",
      strength: "Very Strong",
    },
  ]

  return (
    <div className="space-y-8">
      {/* Password Creation Methods */}
      <div className="bg-white rounded-lg shadow-lg p-8">
        <h3 className="text-2xl font-bold text-gray-800 mb-6 text-center flex items-center justify-center">
          <Key className="w-6 h-6 mr-2 text-blue-600" />
          Password Creation Methods
        </h3>

        <div className="grid md:grid-cols-2 gap-6">
          {creationMethods.map((method, index) => (
            <div
              key={index}
              className="bg-gradient-to-br from-blue-50 to-indigo-50 p-6 rounded-lg border border-blue-200"
            >
              <h4 className="text-lg font-semibold text-blue-800 mb-3">{method.title}</h4>
              <p className="text-sm text-blue-700 mb-3">{method.description}</p>
              <div className="bg-white p-3 rounded border">
                <div className="text-xs text-gray-600 mb-1">Example:</div>
                <div className="text-sm text-gray-800 mb-2">"{method.example}"</div>
                <div className="text-xs text-gray-600 mb-1">Becomes:</div>
                <div className="font-mono text-sm text-green-700 font-semibold">{method.result}</div>
              </div>
              <div className="mt-3">
                <span
                  className={`inline-block px-2 py-1 rounded text-xs font-semibold ${
                    method.strength === "Very Strong"
                      ? "bg-green-100 text-green-800"
                      : method.strength === "Strong"
                        ? "bg-blue-100 text-blue-800"
                        : "bg-yellow-100 text-yellow-800"
                  }`}
                >
                  {method.strength}
                </span>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Security Best Practices */}
      <div className="bg-white rounded-lg shadow-lg p-8">
        <h3 className="text-2xl font-bold text-gray-800 mb-6 text-center flex items-center justify-center">
          <Shield className="w-6 h-6 mr-2 text-green-600" />
          Security Best Practices
        </h3>

        <div className="grid md:grid-cols-3 gap-6">
          {/* Do's */}
          <div className="bg-green-50 p-6 rounded-lg border border-green-200">
            <h4 className="text-lg font-semibold text-green-800 mb-4 flex items-center">
              <Shield className="w-5 h-5 mr-2" />✅ Do This
            </h4>
            <ul className="space-y-3 text-sm text-green-700">
              <li className="flex items-start">
                <span className="text-green-600 mr-2 mt-0.5">•</span>
                <div>Use 12+ characters minimum</div>
              </li>
              <li className="flex items-start">
                <span className="text-green-600 mr-2 mt-0.5">•</span>
                <div>Mix uppercase, lowercase, numbers, symbols</div>
              </li>
              <li className="flex items-start">
                <span className="text-green-600 mr-2 mt-0.5">•</span>
                <div>Use unique passwords for each account</div>
              </li>
              <li className="flex items-start">
                <span className="text-green-600 mr-2 mt-0.5">•</span>
                <div>Enable two-factor authentication</div>
              </li>
              <li className="flex items-start">
                <span className="text-green-600 mr-2 mt-0.5">•</span>
                <div>Use a reputable password manager</div>
              </li>
              <li className="flex items-start">
                <span className="text-green-600 mr-2 mt-0.5">•</span>
                <div>Update passwords regularly</div>
              </li>
            </ul>
          </div>

          {/* Don'ts */}
          <div className="bg-red-50 p-6 rounded-lg border border-red-200">
            <h4 className="text-lg font-semibold text-red-800 mb-4 flex items-center">
              <AlertTriangle className="w-5 h-5 mr-2" />❌ Avoid This
            </h4>
            <ul className="space-y-3 text-sm text-red-700">
              <li className="flex items-start">
                <span className="text-red-600 mr-2 mt-0.5">•</span>
                <div>Personal information (names, dates)</div>
              </li>
              <li className="flex items-start">
                <span className="text-red-600 mr-2 mt-0.5">•</span>
                <div>Dictionary words or common phrases</div>
              </li>
              <li className="flex items-start">
                <span className="text-red-600 mr-2 mt-0.5">•</span>
                <div>Keyboard patterns (qwerty, 123456)</div>
              </li>
              <li className="flex items-start">
                <span className="text-red-600 mr-2 mt-0.5">•</span>
                <div>Reusing passwords across sites</div>
              </li>
              <li className="flex items-start">
                <span className="text-red-600 mr-2 mt-0.5">•</span>
                <div>Sharing passwords via email/text</div>
              </li>
              <li className="flex items-start">
                <span className="text-red-600 mr-2 mt-0.5">•</span>
                <div>Using public computers for sensitive accounts</div>
              </li>
            </ul>
          </div>

          {/* Anti-Tracking */}
          <div className="bg-purple-50 p-6 rounded-lg border border-purple-200">
            <h4 className="text-lg font-semibold text-purple-800 mb-4 flex items-center">
              <Eye className="w-5 h-5 mr-2" />🔒 Anti-Tracking
            </h4>
            <ul className="space-y-3 text-sm text-purple-700">
              <li className="flex items-start">
                <span className="text-purple-600 mr-2 mt-0.5">•</span>
                <div>Avoid social media clues in passwords</div>
              </li>
              <li className="flex items-start">
                <span className="text-purple-600 mr-2 mt-0.5">•</span>
                <div>Use different emails for different services</div>
              </li>
              <li className="flex items-start">
                <span className="text-purple-600 mr-2 mt-0.5">•</span>
                <div>Enable login notifications</div>
              </li>
              <li className="flex items-start">
                <span className="text-purple-600 mr-2 mt-0.5">•</span>
                <div>Review account activity regularly</div>
              </li>
              <li className="flex items-start">
                <span className="text-purple-600 mr-2 mt-0.5">•</span>
                <div>Use VPN on public networks</div>
              </li>
              <li className="flex items-start">
                <span className="text-purple-600 mr-2 mt-0.5">•</span>
                <div>Clear browser data regularly</div>
              </li>
            </ul>
          </div>
        </div>
      </div>

      {/* Password Strength Examples */}
      <div className="bg-white rounded-lg shadow-lg p-8">
        <h3 className="text-2xl font-bold text-gray-800 mb-6 text-center flex items-center justify-center">
          <Zap className="w-6 h-6 mr-2 text-yellow-600" />
          Password Strength Examples
        </h3>

        <div className="grid md:grid-cols-3 gap-6">
          {strengthExamples.map((category, index) => (
            <div
              key={index}
              className={`p-6 rounded-lg border-2 ${
                category.color === "red"
                  ? "bg-red-50 border-red-200"
                  : category.color === "yellow"
                    ? "bg-yellow-50 border-yellow-200"
                    : "bg-green-50 border-green-200"
              }`}
            >
              <h4
                className={`text-lg font-semibold mb-2 ${
                  category.color === "red"
                    ? "text-red-800"
                    : category.color === "yellow"
                      ? "text-yellow-800"
                      : "text-green-800"
                }`}
              >
                {category.color === "red" ? "❌" : category.color === "yellow" ? "⚠️" : "✅"} {category.category}
              </h4>
              <p
                className={`text-sm mb-4 font-medium ${
                  category.color === "red"
                    ? "text-red-700"
                    : category.color === "yellow"
                      ? "text-yellow-700"
                      : "text-green-700"
                }`}
              >
                Time to break: {category.timeToBreak}
              </p>
              <div className="space-y-3">
                {category.examples.map((example, exIndex) => (
                  <div key={exIndex} className="bg-white p-3 rounded border">
                    <div className="font-mono text-sm font-semibold text-gray-800 mb-1">"{example.password}"</div>
                    <div
                      className={`text-xs ${
                        category.color === "red"
                          ? "text-red-600"
                          : category.color === "yellow"
                            ? "text-yellow-600"
                            : "text-green-600"
                      }`}
                    >
                      {example.issue}
                    </div>
                  </div>
                ))}
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Advanced Security Tips */}
      <div className="bg-gradient-to-r from-blue-600 to-purple-600 text-white rounded-lg shadow-lg p-8">
        <h3 className="text-2xl font-bold mb-6 text-center flex items-center justify-center">
          <Lock className="w-6 h-6 mr-2" />
          Advanced Security Tips
        </h3>

        <div className="grid md:grid-cols-2 gap-8">
          <div>
            <h4 className="text-lg font-semibold mb-4 flex items-center">
              <Globe className="w-5 h-5 mr-2" />
              Online Safety
            </h4>
            <ul className="space-y-2 text-sm">
              <li>• Check for HTTPS (🔒) before entering passwords</li>
              <li>• Never enter passwords on suspicious links</li>
              <li>• Use official apps instead of browser when possible</li>
              <li>• Log out of accounts on shared computers</li>
              <li>• Be cautious of phishing emails and fake websites</li>
              <li>• Monitor your accounts for unusual activity</li>
            </ul>
          </div>
          <div>
            <h4 className="text-lg font-semibold mb-4 flex items-center">
              <RefreshCw className="w-5 h-5 mr-2" />
              Password Maintenance
            </h4>
            <ul className="space-y-2 text-sm">
              <li>• Change passwords immediately after breaches</li>
              <li>• Update passwords every 6-12 months</li>
              <li>• Remove accounts you no longer use</li>
              <li>• Keep your password manager updated</li>
              <li>• Backup your password vault securely</li>
              <li>• Test your backup recovery process</li>
            </ul>
          </div>
        </div>

        <div className="mt-8 text-center">
          <div className="bg-white bg-opacity-20 p-4 rounded-lg">
            <p className="text-lg font-semibold mb-2">💡 Pro Tip</p>
            <p className="text-sm">
              The best password is one you don't have to remember! Let 1Dot Password Manager generate, store, and
              auto-fill strong, unique passwords for all your accounts.
            </p>
          </div>
        </div>
      </div>
    </div>
  )
}
